import 'package:ludo_heroes/src/domain/entities/color_entity.dart';
import 'package:ludo_heroes/src/domain/entities/step_entity.dart';

class StepList {
  static final List<StepEntity> _list = [
    StepEntity(
      id: 1,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 0,
      nextBlue: 2,
      nextGreen: 2,
      nextYellow: 2,
    ),
    StepEntity(
      id: 2,
      warna: Warna.red,
      safeZone: true,
      pieces: [],
      nextRed: 3,
      nextBlue: 3,
      nextGreen: 3,
      nextYellow: 3,
    ),
    StepEntity(
      id: 3,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 4,
      nextBlue: 4,
      nextGreen: 4,
      nextYellow: 4,
    ),
    StepEntity(
      id: 4,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 5,
      nextBlue: 5,
      nextGreen: 5,
      nextYellow: 5,
    ),
    StepEntity(
      id: 5,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 6,
      nextBlue: 6,
      nextGreen: 6,
      nextYellow: 6,
    ),
    StepEntity(
      id: 6,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 7,
      nextBlue: 7,
      nextGreen: 7,
      nextYellow: 7,
    ),
    StepEntity(
      id: 7,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 8,
      nextBlue: 8,
      nextGreen: 8,
      nextYellow: 8,
    ),
    StepEntity(
      id: 8,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 9,
      nextBlue: 9,
      nextGreen: 9,
      nextYellow: 9,
    ),
    StepEntity(
      id: 9,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 10,
      nextBlue: 10,
      nextGreen: 10,
      nextYellow: 10,
    ),
    StepEntity(
      id: 10,
      warna: Warna.amber,
      safeZone: true,
      pieces: [],
      nextRed: 11,
      nextBlue: 11,
      nextGreen: 11,
      nextYellow: 11,
    ),
    StepEntity(
      id: 11,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 12,
      nextBlue: 12,
      nextGreen: 12,
      nextYellow: 12,
    ),
    StepEntity(
      id: 12,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 13,
      nextBlue: 13,
      nextGreen: 13,
      nextYellow: 13,
    ),
    StepEntity(
      id: 13,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 14,
      nextBlue: 201,
      nextGreen: 14,
      nextYellow: 14,
    ),
    StepEntity(
      id: 14,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 15,
      nextBlue: 0,
      nextGreen: 15,
      nextYellow: 15,
    ),
    StepEntity(
      id: 15,
      warna: Warna.blue,
      safeZone: true,
      pieces: [],
      nextRed: 16,
      nextBlue: 16,
      nextGreen: 16,
      nextYellow: 16,
    ),
    StepEntity(
      id: 16,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 17,
      nextBlue: 17,
      nextGreen: 17,
      nextYellow: 17,
    ),
    StepEntity(
      id: 17,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 18,
      nextBlue: 18,
      nextGreen: 18,
      nextYellow: 18,
    ),
    StepEntity(
      id: 18,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 19,
      nextBlue: 19,
      nextGreen: 19,
      nextYellow: 19,
    ),
    StepEntity(
      id: 19,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 20,
      nextBlue: 20,
      nextGreen: 20,
      nextYellow: 20,
    ),
    StepEntity(
      id: 20,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 21,
      nextBlue: 21,
      nextGreen: 21,
      nextYellow: 21,
    ),
    StepEntity(
      id: 21,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 22,
      nextBlue: 22,
      nextGreen: 22,
      nextYellow: 22,
    ),
    StepEntity(
      id: 22,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 23,
      nextBlue: 23,
      nextGreen: 23,
      nextYellow: 23,
    ),
    StepEntity(
      id: 23,
      warna: Warna.amber,
      safeZone: true,
      pieces: [],
      nextRed: 24,
      nextBlue: 24,
      nextGreen: 24,
      nextYellow: 24,
    ),
    StepEntity(
      id: 24,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 25,
      nextBlue: 25,
      nextGreen: 25,
      nextYellow: 25,
    ),
    StepEntity(
      id: 25,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 26,
      nextBlue: 26,
      nextGreen: 26,
      nextYellow: 26,
    ),
    StepEntity(
      id: 26,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 27,
      nextBlue: 27,
      nextGreen: 27,
      nextYellow: 401,
    ),
    StepEntity(
      id: 27,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 28,
      nextBlue: 28,
      nextGreen: 28,
      nextYellow: 0,
    ),
    StepEntity(
      id: 28,
      warna: Warna.yellow,
      safeZone: true,
      pieces: [],
      nextRed: 29,
      nextBlue: 29,
      nextGreen: 29,
      nextYellow: 29,
    ),
    StepEntity(
      id: 29,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 30,
      nextBlue: 30,
      nextGreen: 30,
      nextYellow: 30,
    ),
    StepEntity(
      id: 30,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 31,
      nextBlue: 31,
      nextGreen: 31,
      nextYellow: 31,
    ),
    StepEntity(
      id: 31,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 32,
      nextBlue: 32,
      nextGreen: 32,
      nextYellow: 32,
    ),
    StepEntity(
      id: 32,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 33,
      nextBlue: 33,
      nextGreen: 33,
      nextYellow: 33,
    ),
    StepEntity(
      id: 33,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 34,
      nextBlue: 34,
      nextGreen: 34,
      nextYellow: 34,
    ),
    StepEntity(
      id: 34,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 35,
      nextBlue: 35,
      nextGreen: 35,
      nextYellow: 35,
    ),
    StepEntity(
      id: 35,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 36,
      nextBlue: 36,
      nextGreen: 36,
      nextYellow: 36,
    ),
    StepEntity(
      id: 36,
      warna: Warna.amber,
      safeZone: true,
      pieces: [],
      nextRed: 37,
      nextBlue: 37,
      nextGreen: 37,
      nextYellow: 37,
    ),
    StepEntity(
      id: 37,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 38,
      nextBlue: 38,
      nextGreen: 38,
      nextYellow: 38,
    ),
    StepEntity(
      id: 38,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 39,
      nextBlue: 39,
      nextGreen: 39,
      nextYellow: 39,
    ),
    StepEntity(
      id: 39,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 40,
      nextBlue: 40,
      nextGreen: 301,
      nextYellow: 40,
    ),
    StepEntity(
      id: 40,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 41,
      nextBlue: 41,
      nextGreen: 0,
      nextYellow: 41,
    ),
    StepEntity(
      id: 41,
      warna: Warna.green,
      safeZone: true,
      pieces: [],
      nextRed: 42,
      nextBlue: 42,
      nextGreen: 42,
      nextYellow: 42,
    ),
    StepEntity(
      id: 42,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 43,
      nextBlue: 43,
      nextGreen: 43,
      nextYellow: 43,
    ),
    StepEntity(
      id: 43,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 44,
      nextBlue: 44,
      nextGreen: 44,
      nextYellow: 44,
    ),
    StepEntity(
      id: 44,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 45,
      nextBlue: 45,
      nextGreen: 45,
      nextYellow: 45,
    ),
    StepEntity(
      id: 45,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 46,
      nextBlue: 46,
      nextGreen: 46,
      nextYellow: 46,
    ),
    StepEntity(
      id: 46,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 47,
      nextBlue: 47,
      nextGreen: 47,
      nextYellow: 47,
    ),
    StepEntity(
      id: 47,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 48,
      nextBlue: 48,
      nextGreen: 48,
      nextYellow: 48,
    ),
    StepEntity(
      id: 48,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 49,
      nextBlue: 49,
      nextGreen: 49,
      nextYellow: 49,
    ),
    StepEntity(
      id: 49,
      warna: Warna.amber,
      safeZone: true,
      pieces: [],
      nextRed: 50,
      nextBlue: 50,
      nextGreen: 50,
      nextYellow: 50,
    ),
    StepEntity(
      id: 50,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 51,
      nextBlue: 51,
      nextGreen: 51,
      nextYellow: 51,
    ),
    StepEntity(
      id: 51,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 52,
      nextBlue: 52,
      nextGreen: 52,
      nextYellow: 52,
    ),
    StepEntity(
      id: 52,
      warna: Warna.white,
      safeZone: false,
      pieces: [],
      nextRed: 101,
      nextBlue: 1,
      nextGreen: 1,
      nextYellow: 1,
    ),
    StepEntity(
      id: 101,
      warna: Warna.red,
      safeZone: true,
      pieces: [],
      nextRed: 102,
      nextBlue: 0,
      nextGreen: 0,
      nextYellow: 0,
    ),
    StepEntity(
      id: 102,
      warna: Warna.red,
      safeZone: true,
      pieces: [],
      nextRed: 103,
      nextBlue: 0,
      nextGreen: 0,
      nextYellow: 0,
    ),
    StepEntity(
      id: 103,
      warna: Warna.red,
      safeZone: true,
      pieces: [],
      nextRed: 104,
      nextBlue: 0,
      nextGreen: 0,
      nextYellow: 0,
    ),
    StepEntity(
      id: 104,
      warna: Warna.red,
      safeZone: true,
      pieces: [],
      nextRed: 105,
      nextBlue: 0,
      nextGreen: 0,
      nextYellow: 0,
    ),
    StepEntity(
      id: 105,
      warna: Warna.red,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 0,
      nextGreen: 0,
      nextYellow: 0,
    ),
    StepEntity(
      id: 201,
      warna: Warna.blue,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 202,
      nextGreen: 0,
      nextYellow: 0,
    ),
    StepEntity(
      id: 202,
      warna: Warna.blue,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 203,
      nextGreen: 0,
      nextYellow: 0,
    ),
    StepEntity(
      id: 203,
      warna: Warna.blue,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 204,
      nextGreen: 0,
      nextYellow: 0,
    ),
    StepEntity(
      id: 204,
      warna: Warna.blue,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 205,
      nextGreen: 0,
      nextYellow: 0,
    ),
    StepEntity(
      id: 205,
      warna: Warna.blue,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 0,
      nextGreen: 0,
      nextYellow: 0,
    ),
    StepEntity(
      id: 301,
      warna: Warna.green,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 0,
      nextGreen: 302,
      nextYellow: 0,
    ),
    StepEntity(
      id: 302,
      warna: Warna.green,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 0,
      nextGreen: 303,
      nextYellow: 0,
    ),
    StepEntity(
      id: 303,
      warna: Warna.green,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 0,
      nextGreen: 304,
      nextYellow: 0,
    ),
    StepEntity(
      id: 304,
      warna: Warna.green,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 0,
      nextGreen: 305,
      nextYellow: 0,
    ),
    StepEntity(
      id: 305,
      warna: Warna.green,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 0,
      nextGreen: 0,
      nextYellow: 0,
    ),
    StepEntity(
      id: 401,
      warna: Warna.yellow,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 0,
      nextGreen: 0,
      nextYellow: 402,
    ),
    StepEntity(
      id: 402,
      warna: Warna.yellow,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 0,
      nextGreen: 0,
      nextYellow: 403,
    ),
    StepEntity(
      id: 403,
      warna: Warna.yellow,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 0,
      nextGreen: 0,
      nextYellow: 404,
    ),
    StepEntity(
      id: 404,
      warna: Warna.yellow,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 0,
      nextGreen: 0,
      nextYellow: 405,
    ),
    StepEntity(
      id: 405,
      warna: Warna.yellow,
      safeZone: true,
      pieces: [],
      nextRed: 0,
      nextBlue: 0,
      nextGreen: 0,
      nextYellow: 0,
    ),
  ];

  static List<StepEntity> getData() {
    return _list;
  }
}
